// <auto-generated />
using System;
using BouncerBot.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BouncerBot.Db.Migrations
{
    [DbContext(typeof(BouncerBotDbContext))]
    [Migration("20250819171702_Add-AchievementMessageCompositeKey")]
    partial class AddAchievementMessageCompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BouncerBot.Db.Models.AchievementLogChannelOverride", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AchievementRole")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "AchievementRole");

                    b.ToTable("AchievementLogOverrides");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.AchievementMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AchievementRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "AchievementRole");

                    b.ToTable("AchievementMessages");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.BannedHunter", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("MouseHuntId", "GuildId");

                    b.ToTable("BannedHunters");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.LogChannelsSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("GeneralId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("VerificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("LogSettings");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.RoleSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "Role");

                    b.ToTable("RoleSettings");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.Snuid", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnuId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MouseHuntId");

                    b.ToTable("SnuidCache");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerificationHistory", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordIdHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MouseHuntIdHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "DiscordIdHash");

                    b.HasIndex("GuildId", "MouseHuntIdHash")
                        .IsUnique();

                    b.ToTable("VerificationHistory");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifiedUser", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerifyMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId", "DiscordId");

                    b.HasIndex("VerifyMessageId")
                        .IsUnique();

                    b.HasIndex("GuildId", "MouseHuntId")
                        .IsUnique();

                    b.ToTable("VerifiedUsers");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifyMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VerifyMessages");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifySetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("VerifySettings");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifiedUser", b =>
                {
                    b.HasOne("BouncerBot.Db.Models.VerifyMessage", "VerifyMessage")
                        .WithOne()
                        .HasForeignKey("BouncerBot.Db.Models.VerifiedUser", "VerifyMessageId");

                    b.Navigation("VerifyMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
