// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonstroBot.Db;

#nullable disable

namespace MonstroBot.Db.Migrations
{
    [DbContext(typeof(MonstroBotDbContext))]
    [Migration("20250706180411_AddVerifiedTradeMapBanned")]
    partial class AddVerifiedTradeMapBanned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MonstroBot.Db.Models.AchievementMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArcaneMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checkmark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crown")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraconicMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("EggMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForgottenMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("HyderoMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("MultiMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiftMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShadowMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Star")
                        .HasColumnType("TEXT");

                    b.Property<string>("TacticalMaster")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("AchievementMessages");
                });

            modelBuilder.Entity("MonstroBot.Db.Models.LogSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EggMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("FlexId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LogId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("VerificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("LogSettings");
                });

            modelBuilder.Entity("MonstroBot.Db.Models.RoleSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ArcaneMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CheckmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CrownId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DraconicMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EggMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ForgottenMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("HydroMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LawMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("MapBannedId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("MultiMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("PhysicalMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RiftMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ShadowMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("StarId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TacticalMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TradeBannedId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("VerifiedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("RoleSettings");
                });

            modelBuilder.Entity("MonstroBot.Db.Models.VerifiedUser", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MouseHuntId", "GuildId", "DiscordId");

                    b.HasIndex("GuildId", "DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId", "MouseHuntId")
                        .IsUnique();

                    b.ToTable("VerifiedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
