// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonstroBot.Db;

#nullable disable

namespace MonstroBot.Db.Migrations
{
    [DbContext(typeof(MonstroBotDbContext))]
    partial class MonstroBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MonstroBot.Db.Models.VerifiedUser", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MouseHuntId", "GuildId", "DiscordId");

                    b.HasIndex("GuildId", "DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId", "MouseHuntId")
                        .IsUnique();

                    b.ToTable("VerifiedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
