// <auto-generated />
using System;
using BouncerBot.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BouncerBot.Db.Migrations
{
    [DbContext(typeof(BouncerBotDbContext))]
    [Migration("20250729214152_Add-BannedHunters")]
    partial class AddBannedHunters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BouncerBot.Db.Models.AchievementMessage", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArcaneMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Checkmark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crown")
                        .HasColumnType("TEXT");

                    b.Property<string>("DraconicMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("EggMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForgottenMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("HydroMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("LawMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("MultiMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiftMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShadowMaster")
                        .HasColumnType("TEXT");

                    b.Property<string>("Star")
                        .HasColumnType("TEXT");

                    b.Property<string>("TacticalMaster")
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("AchievementMessages");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.BannedHunter", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("MouseHuntId", "GuildId");

                    b.ToTable("BannedHunters");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.LogSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EggMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("FlexId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LogId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("VerificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("LogSettings");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.RoleSetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("AchieverId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ArcaneMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CheckmarkId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("CrownId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("DraconicMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EggMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ForgottenMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("HydroMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("LawMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("MapBannedId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("MultiMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("PhysicalMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("RiftMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ShadowMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("StarId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TacticalMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("TradeBannedId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("VerifiedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("RoleSettings");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.Snuid", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnuId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MouseHuntId");

                    b.ToTable("SnuidCache");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerificationHistory", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MouseHuntIdHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId", "DiscordId");

                    b.ToTable("VerificationHistory");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifiedUser", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VerifyMessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MouseHuntId", "GuildId", "DiscordId");

                    b.HasIndex("VerifyMessageId")
                        .IsUnique();

                    b.HasIndex("GuildId", "DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId", "MouseHuntId")
                        .IsUnique();

                    b.ToTable("VerifiedUsers");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifyMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VerifyMessages");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifySetting", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("VerifySettings");
                });

            modelBuilder.Entity("BouncerBot.Db.Models.VerifiedUser", b =>
                {
                    b.HasOne("BouncerBot.Db.Models.VerifyMessage", "VerifyMessage")
                        .WithOne()
                        .HasForeignKey("BouncerBot.Db.Models.VerifiedUser", "VerifyMessageId");

                    b.Navigation("VerifyMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
