// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BouncerBot.Db;

#nullable disable

namespace BouncerBot.Db.Migrations
{
    [DbContext(typeof(BouncerBotDbContext))]
    [Migration("20250625211315_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BouncerBot.Db.Models.VerifiedUser", b =>
                {
                    b.Property<uint>("MouseHuntId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MouseHuntId", "GuildId", "DiscordId");

                    b.HasIndex("GuildId", "DiscordId")
                        .IsUnique();

                    b.HasIndex("GuildId", "MouseHuntId")
                        .IsUnique();

                    b.ToTable("VerifiedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
