name: Cloudflare Deployment

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/cloudflare.yml
      - worker/**
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: "prod"
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        working-directory: ./worker
        run: bun install
      - name: Deploy to production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: ./worker
          command: deploy
