name: Dotnet Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - .github/workflows/dotnet.yml
      - bot/**

jobs:
  build:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Test
        working-directory: ./bot
        run: dotnet test

      - name: Publish
        working-directory: ./bot
        run: dotnet publish src/BouncerBot/BouncerBot.csproj --output ./publish --self-contained -r linux-x64 -p:PublishSingleFile=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bouncerbot-publish
          path: ./bot/publish
          retention-days: 30

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bouncerbot-publish
          path: ./publish

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_KEY }}
          name: id_ed25519
          known_hosts: '${{ secrets.KNOWN_HOSTS }}'

      - name: Deploy via rsync
        run: |
          rsync -avz \
            -e "ssh -p ${{ secrets.DO_PORT }}" \
            ./publish/ ${{ secrets.DO_USER }}@${{ secrets.DO_IP }}:~/BouncerBot/

      - name: Start service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.DO_KEY }}
          script: |
            chmod +x ~/BouncerBot/BouncerBot
            echo ${{ secrets.DO_PASS }} | sudo -S systemctl restart bouncerbot
            echo ${{ secrets.DO_PASS }} | sudo -S systemctl is-active bouncerbot
