name: Dotnet Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - .github/workflows/dotnet.yml
      - bot/**

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish
        working-directory: ./bot
        run: dotnet publish src/BouncerBot/BouncerBot.csproj --output ./publish --self-contained -r linux-x64 -p:PublishSingleFile=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bouncerbot-publish
          path: ./bot/publish
          retention-days: 30

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bouncerbot-publish
          path: ./publish

      - name: Stop service and prepare directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.DO_KEY }}
          script: |
            echo ${{ secrets.DO_PASS }} | sudo -S systemctl stop bouncerbot || true

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.DO_PORT }} ${{ secrets.DO_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz \
            -e "ssh -p ${{ secrets.DO_PORT }}" \
            ./publish/ ${{ secrets.DO_USER }}@${{ secrets.DO_IP }}:~/BouncerBot/

      - name: Start service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_IP }}
          username: ${{ secrets.DO_USER }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.DO_KEY }}
          script: |
            chmod +x ~/BouncerBot/BouncerBot
            echo ${{ secrets.DO_PASS }} | sudo -S systemctl start bouncerbot
            echo ${{ secrets.DO_PASS }} | sudo systemctl is-active bouncerbot
